language: rust
sudo: false
rust:
  - 1.5.0
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script:
  - pip install 'travis-cargo<0.2' --user

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - PATH=$HOME/.local/bin:$PATH
    - secure: "Ez5eIIgmsfNoV9NQ9H6KrAYX/Dxx6EUQEyyLMoSFvgJuMaPsyWlsDQDKbl9G+aNDNdSWYtYVFc4/fCW+H7a13HjVwB2CH2mChHSeguO8FSAkWns8tkZ+71SKL5/hg3Ig2m+kvfDjjV1O8seFEgTDP3enHFoRTmBSZHeNryo1ITM="

script:
  - |
    travis-cargo build &&
    travis-cargo test &&
    travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify

notifications:
  webhooks: http://rust-embedded-bot.herokuapp.com/travis
