[package]

name = "sysfs_gpio"
version = "0.1.0"
authors = ["Paul Osborne <osbpau@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/posborne/rust-sysfs-gpio"
homepage = "https://github.com/posborne/rust-sysfs-gpio"
description = """
Provides access to the Linux sysfs interface to GPIOs.
Includes a low-level interface as well as a higher-level
and more managed interface for reading, writing, and
polling on GPIO interrupts
"""
